### PR TITLE
Make compatible with acquia/blt-behat

### PR DESCRIPTION
**Pull request by greggmarshall**
Changes necessary to make this compatible with BLT 12 with acquia/blt-behat

### CODE REVIEW

**Comment by drewble** [comment]
Thanks for these changes. Just what I needed to get this package up to spec with BLT 12. It would be great to get this merged into the package so we don't need a patch.

**Comment by mikejoconnor** [comment]
It would be helpful to add  acquia/blt and acquia/blt-behat as a depenency

`    "require": {
        "acquia/blt": "^12",
        "acquia/blt-behat": "^1.1",`

**Comment by greggmarshall** [comment]
@mikejoconnor Good idea, added

**Comment by greggmarshall** [comment]
Giving up

**Pull request closed without merging**
